### ISSUE TITLE
Properties without getter

### ISSUE THREAD

**Issue by kip-dk** [kip-dk/Kipon.Excel#1]
Properties without getter is causing an exception. Such property should simply bee ignored.

Error: Property Get method was not found.
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Kipon.Excel.WriterImplementation.Models.Sheet.PropertySheet.SetCurrent()
   at Kipon.Excel.WriterImplementation.Models.Sheet.PropertySheet.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Kipon.Excel.WriterImplementation.OpenXml.OpenXmlWriter.generateWorksheetPartContent(WorksheetPart worksheetPart, ISheet sheet)
   at Kipon.Excel.WriterImplementation.OpenXml.OpenXmlWriter.createParts(SpreadsheetDocument document)
   at Kipon.Excel.WriterImplementation.OpenXml.OpenXmlWriter.Serialize(Stream stream)
   at Kipon.Excel.Linq.LinqWriterInterface.ToExcel[T](T data, Stream excel)

**Comment by kip-dk** [comment]
Solved in version 1.0.7.0
